name: mi_presupuesto
description: "presupuesto mensual Jorge Charrupi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Acepta desde tu versiÃ³n actual
  flutter: "3.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagen/icono.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/icono.png